### ISSUE TITLE
Support ERC-20, ERC-223 and ERC-721 tokens

### ISSUE THREAD

**Issue by HarryR** [HarryR/shwop#4]
To play nicely with the Ethereum token and asset economy the HTLC contract needs to support the various widely used token standards.

The core HTLC logic should be separated into it's own contract, which can then be used by frontend contracts for the specific token.

## TODO

 - [ ] add `address token` to `Exchange` struct
 - [ ] When `token == address(0x0)` it's Ether? Or separate contract for Ether.
 - [ ] Write tests for ERC-20 token
 - [ ] Python client support for the supported tokens
 - [ ] Include token address in `HASH(...) = exchGUID`
